// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PrivateProtocol.proto

package test.com.google.protobuf.proto;

public final class PrivateProtocol {
  private PrivateProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.com.google.protobuf.proto.Protocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.test.com.google.protobuf.proto.Head action = 1;</code>
     */
    boolean hasHead();
    /**
     * <code>.test.com.google.protobuf.proto.Head action = 1;</code>
     */
    test.com.google.protobuf.proto.ProtocolHead.Head getHead();
    /**
     * <code>.test.com.google.protobuf.proto.Head action = 1;</code>
     */
    test.com.google.protobuf.proto.ProtocolHead.HeadOrBuilder getHeadOrBuilder();

    /**
     * <code>.test.com.google.protobuf.proto.BodyOne bodyOne = 11;</code>
     */
    boolean hasBodyOne();
    /**
     * <code>.test.com.google.protobuf.proto.BodyOne bodyOne = 11;</code>
     */
    test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne getBodyOne();
    /**
     * <code>.test.com.google.protobuf.proto.BodyOne bodyOne = 11;</code>
     */
    test.com.google.protobuf.proto.ProtocolBodyOne.BodyOneOrBuilder getBodyOneOrBuilder();

    /**
     * <code>.test.com.google.protobuf.proto.BodyChat bodyChat = 12;</code>
     */
    boolean hasBodyChat();
    /**
     * <code>.test.com.google.protobuf.proto.BodyChat bodyChat = 12;</code>
     */
    test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat getBodyChat();
    /**
     * <code>.test.com.google.protobuf.proto.BodyChat bodyChat = 12;</code>
     */
    test.com.google.protobuf.proto.ProtocolBodyChat.BodyChatOrBuilder getBodyChatOrBuilder();

    public test.com.google.protobuf.proto.PrivateProtocol.Protocol.BodyCase getBodyCase();
  }
  /**
   * Protobuf type {@code test.com.google.protobuf.proto.Protocol}
   */
  public  static final class Protocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.com.google.protobuf.proto.Protocol)
      ProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Protocol.newBuilder() to construct.
    private Protocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Protocol() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Protocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              test.com.google.protobuf.proto.ProtocolHead.Head.Builder subBuilder = null;
              if (head_ != null) {
                subBuilder = head_.toBuilder();
              }
              head_ = input.readMessage(test.com.google.protobuf.proto.ProtocolHead.Head.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(head_);
                head_ = subBuilder.buildPartial();
              }

              break;
            }
            case 90: {
              test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.Builder subBuilder = null;
              if (bodyCase_ == 11) {
                subBuilder = ((test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne) body_).toBuilder();
              }
              body_ =
                  input.readMessage(test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 11;
              break;
            }
            case 98: {
              test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.Builder subBuilder = null;
              if (bodyCase_ == 12) {
                subBuilder = ((test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat) body_).toBuilder();
              }
              body_ =
                  input.readMessage(test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 12;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.com.google.protobuf.proto.PrivateProtocol.internal_static_test_com_google_protobuf_proto_Protocol_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.com.google.protobuf.proto.PrivateProtocol.internal_static_test_com_google_protobuf_proto_Protocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.com.google.protobuf.proto.PrivateProtocol.Protocol.class, test.com.google.protobuf.proto.PrivateProtocol.Protocol.Builder.class);
    }

    private int bodyCase_ = 0;
    private java.lang.Object body_;
    public enum BodyCase
        implements com.google.protobuf.Internal.EnumLite {
      BODYONE(11),
      BODYCHAT(12),
      BODY_NOT_SET(0);
      private final int value;
      private BodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static BodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static BodyCase forNumber(int value) {
        switch (value) {
          case 11: return BODYONE;
          case 12: return BODYCHAT;
          case 0: return BODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public BodyCase
    getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    public static final int HEAD_FIELD_NUMBER = 1;
    private test.com.google.protobuf.proto.ProtocolHead.Head head_;
    /**
     * <code>.test.com.google.protobuf.proto.Head action = 1;</code>
     */
    public boolean hasHead() {
      return head_ != null;
    }
    /**
     * <code>.test.com.google.protobuf.proto.Head action = 1;</code>
     */
    public test.com.google.protobuf.proto.ProtocolHead.Head getHead() {
      return head_ == null ? test.com.google.protobuf.proto.ProtocolHead.Head.getDefaultInstance() : head_;
    }
    /**
     * <code>.test.com.google.protobuf.proto.Head action = 1;</code>
     */
    public test.com.google.protobuf.proto.ProtocolHead.HeadOrBuilder getHeadOrBuilder() {
      return getHead();
    }

    public static final int BODYONE_FIELD_NUMBER = 11;
    /**
     * <code>.test.com.google.protobuf.proto.BodyOne bodyOne = 11;</code>
     */
    public boolean hasBodyOne() {
      return bodyCase_ == 11;
    }
    /**
     * <code>.test.com.google.protobuf.proto.BodyOne bodyOne = 11;</code>
     */
    public test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne getBodyOne() {
      if (bodyCase_ == 11) {
         return (test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne) body_;
      }
      return test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.getDefaultInstance();
    }
    /**
     * <code>.test.com.google.protobuf.proto.BodyOne bodyOne = 11;</code>
     */
    public test.com.google.protobuf.proto.ProtocolBodyOne.BodyOneOrBuilder getBodyOneOrBuilder() {
      if (bodyCase_ == 11) {
         return (test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne) body_;
      }
      return test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.getDefaultInstance();
    }

    public static final int BODYCHAT_FIELD_NUMBER = 12;
    /**
     * <code>.test.com.google.protobuf.proto.BodyChat bodyChat = 12;</code>
     */
    public boolean hasBodyChat() {
      return bodyCase_ == 12;
    }
    /**
     * <code>.test.com.google.protobuf.proto.BodyChat bodyChat = 12;</code>
     */
    public test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat getBodyChat() {
      if (bodyCase_ == 12) {
         return (test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat) body_;
      }
      return test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.getDefaultInstance();
    }
    /**
     * <code>.test.com.google.protobuf.proto.BodyChat bodyChat = 12;</code>
     */
    public test.com.google.protobuf.proto.ProtocolBodyChat.BodyChatOrBuilder getBodyChatOrBuilder() {
      if (bodyCase_ == 12) {
         return (test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat) body_;
      }
      return test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (head_ != null) {
        output.writeMessage(1, getHead());
      }
      if (bodyCase_ == 11) {
        output.writeMessage(11, (test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne) body_);
      }
      if (bodyCase_ == 12) {
        output.writeMessage(12, (test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat) body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (head_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHead());
      }
      if (bodyCase_ == 11) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, (test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne) body_);
      }
      if (bodyCase_ == 12) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, (test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat) body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.com.google.protobuf.proto.PrivateProtocol.Protocol)) {
        return super.equals(obj);
      }
      test.com.google.protobuf.proto.PrivateProtocol.Protocol other = (test.com.google.protobuf.proto.PrivateProtocol.Protocol) obj;

      if (hasHead() != other.hasHead()) return false;
      if (hasHead()) {
        if (!getHead()
            .equals(other.getHead())) return false;
      }
      if (!getBodyCase().equals(other.getBodyCase())) return false;
      switch (bodyCase_) {
        case 11:
          if (!getBodyOne()
              .equals(other.getBodyOne())) return false;
          break;
        case 12:
          if (!getBodyChat()
              .equals(other.getBodyChat())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHead()) {
        hash = (37 * hash) + HEAD_FIELD_NUMBER;
        hash = (53 * hash) + getHead().hashCode();
      }
      switch (bodyCase_) {
        case 11:
          hash = (37 * hash) + BODYONE_FIELD_NUMBER;
          hash = (53 * hash) + getBodyOne().hashCode();
          break;
        case 12:
          hash = (37 * hash) + BODYCHAT_FIELD_NUMBER;
          hash = (53 * hash) + getBodyChat().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.com.google.protobuf.proto.PrivateProtocol.Protocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.com.google.protobuf.proto.PrivateProtocol.Protocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.PrivateProtocol.Protocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.com.google.protobuf.proto.PrivateProtocol.Protocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.PrivateProtocol.Protocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.com.google.protobuf.proto.PrivateProtocol.Protocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.PrivateProtocol.Protocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.com.google.protobuf.proto.PrivateProtocol.Protocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.PrivateProtocol.Protocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.com.google.protobuf.proto.PrivateProtocol.Protocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.PrivateProtocol.Protocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.com.google.protobuf.proto.PrivateProtocol.Protocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.com.google.protobuf.proto.PrivateProtocol.Protocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.com.google.protobuf.proto.Protocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.com.google.protobuf.proto.Protocol)
        test.com.google.protobuf.proto.PrivateProtocol.ProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.com.google.protobuf.proto.PrivateProtocol.internal_static_test_com_google_protobuf_proto_Protocol_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.com.google.protobuf.proto.PrivateProtocol.internal_static_test_com_google_protobuf_proto_Protocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.com.google.protobuf.proto.PrivateProtocol.Protocol.class, test.com.google.protobuf.proto.PrivateProtocol.Protocol.Builder.class);
      }

      // Construct using test.com.google.protobuf.proto.PrivateProtocol.Protocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headBuilder_ == null) {
          head_ = null;
        } else {
          head_ = null;
          headBuilder_ = null;
        }
        bodyCase_ = 0;
        body_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.com.google.protobuf.proto.PrivateProtocol.internal_static_test_com_google_protobuf_proto_Protocol_descriptor;
      }

      @java.lang.Override
      public test.com.google.protobuf.proto.PrivateProtocol.Protocol getDefaultInstanceForType() {
        return test.com.google.protobuf.proto.PrivateProtocol.Protocol.getDefaultInstance();
      }

      @java.lang.Override
      public test.com.google.protobuf.proto.PrivateProtocol.Protocol build() {
        test.com.google.protobuf.proto.PrivateProtocol.Protocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.com.google.protobuf.proto.PrivateProtocol.Protocol buildPartial() {
        test.com.google.protobuf.proto.PrivateProtocol.Protocol result = new test.com.google.protobuf.proto.PrivateProtocol.Protocol(this);
        if (headBuilder_ == null) {
          result.head_ = head_;
        } else {
          result.head_ = headBuilder_.build();
        }
        if (bodyCase_ == 11) {
          if (bodyOneBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = bodyOneBuilder_.build();
          }
        }
        if (bodyCase_ == 12) {
          if (bodyChatBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = bodyChatBuilder_.build();
          }
        }
        result.bodyCase_ = bodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.com.google.protobuf.proto.PrivateProtocol.Protocol) {
          return mergeFrom((test.com.google.protobuf.proto.PrivateProtocol.Protocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.com.google.protobuf.proto.PrivateProtocol.Protocol other) {
        if (other == test.com.google.protobuf.proto.PrivateProtocol.Protocol.getDefaultInstance()) return this;
        if (other.hasHead()) {
          mergeHead(other.getHead());
        }
        switch (other.getBodyCase()) {
          case BODYONE: {
            mergeBodyOne(other.getBodyOne());
            break;
          }
          case BODYCHAT: {
            mergeBodyChat(other.getBodyChat());
            break;
          }
          case BODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.com.google.protobuf.proto.PrivateProtocol.Protocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.com.google.protobuf.proto.PrivateProtocol.Protocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bodyCase_ = 0;
      private java.lang.Object body_;
      public BodyCase
          getBodyCase() {
        return BodyCase.forNumber(
            bodyCase_);
      }

      public Builder clearBody() {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
        return this;
      }


      private test.com.google.protobuf.proto.ProtocolHead.Head head_;
      private com.google.protobuf.SingleFieldBuilderV3<
          test.com.google.protobuf.proto.ProtocolHead.Head, test.com.google.protobuf.proto.ProtocolHead.Head.Builder, test.com.google.protobuf.proto.ProtocolHead.HeadOrBuilder> headBuilder_;
      /**
       * <code>.test.com.google.protobuf.proto.Head action = 1;</code>
       */
      public boolean hasHead() {
        return headBuilder_ != null || head_ != null;
      }
      /**
       * <code>.test.com.google.protobuf.proto.Head action = 1;</code>
       */
      public test.com.google.protobuf.proto.ProtocolHead.Head getHead() {
        if (headBuilder_ == null) {
          return head_ == null ? test.com.google.protobuf.proto.ProtocolHead.Head.getDefaultInstance() : head_;
        } else {
          return headBuilder_.getMessage();
        }
      }
      /**
       * <code>.test.com.google.protobuf.proto.Head action = 1;</code>
       */
      public Builder setHead(test.com.google.protobuf.proto.ProtocolHead.Head value) {
        if (headBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          head_ = value;
          onChanged();
        } else {
          headBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.Head action = 1;</code>
       */
      public Builder setHead(
          test.com.google.protobuf.proto.ProtocolHead.Head.Builder builderForValue) {
        if (headBuilder_ == null) {
          head_ = builderForValue.build();
          onChanged();
        } else {
          headBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.Head action = 1;</code>
       */
      public Builder mergeHead(test.com.google.protobuf.proto.ProtocolHead.Head value) {
        if (headBuilder_ == null) {
          if (head_ != null) {
            head_ =
              test.com.google.protobuf.proto.ProtocolHead.Head.newBuilder(head_).mergeFrom(value).buildPartial();
          } else {
            head_ = value;
          }
          onChanged();
        } else {
          headBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.Head action = 1;</code>
       */
      public Builder clearHead() {
        if (headBuilder_ == null) {
          head_ = null;
          onChanged();
        } else {
          head_ = null;
          headBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.Head action = 1;</code>
       */
      public test.com.google.protobuf.proto.ProtocolHead.Head.Builder getHeadBuilder() {
        
        onChanged();
        return getHeadFieldBuilder().getBuilder();
      }
      /**
       * <code>.test.com.google.protobuf.proto.Head action = 1;</code>
       */
      public test.com.google.protobuf.proto.ProtocolHead.HeadOrBuilder getHeadOrBuilder() {
        if (headBuilder_ != null) {
          return headBuilder_.getMessageOrBuilder();
        } else {
          return head_ == null ?
              test.com.google.protobuf.proto.ProtocolHead.Head.getDefaultInstance() : head_;
        }
      }
      /**
       * <code>.test.com.google.protobuf.proto.Head action = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          test.com.google.protobuf.proto.ProtocolHead.Head, test.com.google.protobuf.proto.ProtocolHead.Head.Builder, test.com.google.protobuf.proto.ProtocolHead.HeadOrBuilder> 
          getHeadFieldBuilder() {
        if (headBuilder_ == null) {
          headBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              test.com.google.protobuf.proto.ProtocolHead.Head, test.com.google.protobuf.proto.ProtocolHead.Head.Builder, test.com.google.protobuf.proto.ProtocolHead.HeadOrBuilder>(
                  getHead(),
                  getParentForChildren(),
                  isClean());
          head_ = null;
        }
        return headBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne, test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.Builder, test.com.google.protobuf.proto.ProtocolBodyOne.BodyOneOrBuilder> bodyOneBuilder_;
      /**
       * <code>.test.com.google.protobuf.proto.BodyOne bodyOne = 11;</code>
       */
      public boolean hasBodyOne() {
        return bodyCase_ == 11;
      }
      /**
       * <code>.test.com.google.protobuf.proto.BodyOne bodyOne = 11;</code>
       */
      public test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne getBodyOne() {
        if (bodyOneBuilder_ == null) {
          if (bodyCase_ == 11) {
            return (test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne) body_;
          }
          return test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.getDefaultInstance();
        } else {
          if (bodyCase_ == 11) {
            return bodyOneBuilder_.getMessage();
          }
          return test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.getDefaultInstance();
        }
      }
      /**
       * <code>.test.com.google.protobuf.proto.BodyOne bodyOne = 11;</code>
       */
      public Builder setBodyOne(test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne value) {
        if (bodyOneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyOneBuilder_.setMessage(value);
        }
        bodyCase_ = 11;
        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.BodyOne bodyOne = 11;</code>
       */
      public Builder setBodyOne(
          test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.Builder builderForValue) {
        if (bodyOneBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyOneBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 11;
        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.BodyOne bodyOne = 11;</code>
       */
      public Builder mergeBodyOne(test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne value) {
        if (bodyOneBuilder_ == null) {
          if (bodyCase_ == 11 &&
              body_ != test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.getDefaultInstance()) {
            body_ = test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.newBuilder((test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 11) {
            bodyOneBuilder_.mergeFrom(value);
          }
          bodyOneBuilder_.setMessage(value);
        }
        bodyCase_ = 11;
        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.BodyOne bodyOne = 11;</code>
       */
      public Builder clearBodyOne() {
        if (bodyOneBuilder_ == null) {
          if (bodyCase_ == 11) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 11) {
            bodyCase_ = 0;
            body_ = null;
          }
          bodyOneBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.BodyOne bodyOne = 11;</code>
       */
      public test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.Builder getBodyOneBuilder() {
        return getBodyOneFieldBuilder().getBuilder();
      }
      /**
       * <code>.test.com.google.protobuf.proto.BodyOne bodyOne = 11;</code>
       */
      public test.com.google.protobuf.proto.ProtocolBodyOne.BodyOneOrBuilder getBodyOneOrBuilder() {
        if ((bodyCase_ == 11) && (bodyOneBuilder_ != null)) {
          return bodyOneBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 11) {
            return (test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne) body_;
          }
          return test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.getDefaultInstance();
        }
      }
      /**
       * <code>.test.com.google.protobuf.proto.BodyOne bodyOne = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne, test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.Builder, test.com.google.protobuf.proto.ProtocolBodyOne.BodyOneOrBuilder> 
          getBodyOneFieldBuilder() {
        if (bodyOneBuilder_ == null) {
          if (!(bodyCase_ == 11)) {
            body_ = test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.getDefaultInstance();
          }
          bodyOneBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne, test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.Builder, test.com.google.protobuf.proto.ProtocolBodyOne.BodyOneOrBuilder>(
                  (test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 11;
        onChanged();;
        return bodyOneBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat, test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.Builder, test.com.google.protobuf.proto.ProtocolBodyChat.BodyChatOrBuilder> bodyChatBuilder_;
      /**
       * <code>.test.com.google.protobuf.proto.BodyChat bodyChat = 12;</code>
       */
      public boolean hasBodyChat() {
        return bodyCase_ == 12;
      }
      /**
       * <code>.test.com.google.protobuf.proto.BodyChat bodyChat = 12;</code>
       */
      public test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat getBodyChat() {
        if (bodyChatBuilder_ == null) {
          if (bodyCase_ == 12) {
            return (test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat) body_;
          }
          return test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.getDefaultInstance();
        } else {
          if (bodyCase_ == 12) {
            return bodyChatBuilder_.getMessage();
          }
          return test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.getDefaultInstance();
        }
      }
      /**
       * <code>.test.com.google.protobuf.proto.BodyChat bodyChat = 12;</code>
       */
      public Builder setBodyChat(test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat value) {
        if (bodyChatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyChatBuilder_.setMessage(value);
        }
        bodyCase_ = 12;
        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.BodyChat bodyChat = 12;</code>
       */
      public Builder setBodyChat(
          test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.Builder builderForValue) {
        if (bodyChatBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyChatBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 12;
        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.BodyChat bodyChat = 12;</code>
       */
      public Builder mergeBodyChat(test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat value) {
        if (bodyChatBuilder_ == null) {
          if (bodyCase_ == 12 &&
              body_ != test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.getDefaultInstance()) {
            body_ = test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.newBuilder((test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 12) {
            bodyChatBuilder_.mergeFrom(value);
          }
          bodyChatBuilder_.setMessage(value);
        }
        bodyCase_ = 12;
        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.BodyChat bodyChat = 12;</code>
       */
      public Builder clearBodyChat() {
        if (bodyChatBuilder_ == null) {
          if (bodyCase_ == 12) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 12) {
            bodyCase_ = 0;
            body_ = null;
          }
          bodyChatBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.BodyChat bodyChat = 12;</code>
       */
      public test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.Builder getBodyChatBuilder() {
        return getBodyChatFieldBuilder().getBuilder();
      }
      /**
       * <code>.test.com.google.protobuf.proto.BodyChat bodyChat = 12;</code>
       */
      public test.com.google.protobuf.proto.ProtocolBodyChat.BodyChatOrBuilder getBodyChatOrBuilder() {
        if ((bodyCase_ == 12) && (bodyChatBuilder_ != null)) {
          return bodyChatBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 12) {
            return (test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat) body_;
          }
          return test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.getDefaultInstance();
        }
      }
      /**
       * <code>.test.com.google.protobuf.proto.BodyChat bodyChat = 12;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat, test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.Builder, test.com.google.protobuf.proto.ProtocolBodyChat.BodyChatOrBuilder> 
          getBodyChatFieldBuilder() {
        if (bodyChatBuilder_ == null) {
          if (!(bodyCase_ == 12)) {
            body_ = test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.getDefaultInstance();
          }
          bodyChatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat, test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.Builder, test.com.google.protobuf.proto.ProtocolBodyChat.BodyChatOrBuilder>(
                  (test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 12;
        onChanged();;
        return bodyChatBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.com.google.protobuf.proto.Protocol)
    }

    // @@protoc_insertion_point(class_scope:test.com.google.protobuf.proto.Protocol)
    private static final test.com.google.protobuf.proto.PrivateProtocol.Protocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.com.google.protobuf.proto.PrivateProtocol.Protocol();
    }

    public static test.com.google.protobuf.proto.PrivateProtocol.Protocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Protocol>
        PARSER = new com.google.protobuf.AbstractParser<Protocol>() {
      @java.lang.Override
      public Protocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Protocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Protocol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Protocol> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.com.google.protobuf.proto.PrivateProtocol.Protocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_com_google_protobuf_proto_Protocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_com_google_protobuf_proto_Protocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025PrivateProtocol.proto\022\036test.com.google" +
      ".protobuf.proto\032\022ProtocolHead.proto\032\025Pro" +
      "tocolBodyOne.proto\032\026ProtocolBodyChat.pro" +
      "to\"\300\001\n\010Protocol\0222\n\004head\030\001 \001(\0132$.test.com" +
      ".google.protobuf.proto.Head\022:\n\007bodyOne\030\013" +
      " \001(\0132\'.test.com.google.protobuf.proto.Bo" +
      "dyOneH\000\022<\n\010bodyChat\030\014 \001(\0132(.test.com.goo" +
      "gle.protobuf.proto.BodyChatH\000B\006\n\004bodyB\021B" +
      "\017PrivateProtocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          test.com.google.protobuf.proto.ProtocolHead.getDescriptor(),
          test.com.google.protobuf.proto.ProtocolBodyOne.getDescriptor(),
          test.com.google.protobuf.proto.ProtocolBodyChat.getDescriptor(),
        }, assigner);
    internal_static_test_com_google_protobuf_proto_Protocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_com_google_protobuf_proto_Protocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_com_google_protobuf_proto_Protocol_descriptor,
        new java.lang.String[] { "Head", "BodyOne", "BodyChat", "Body", });
    test.com.google.protobuf.proto.ProtocolHead.getDescriptor();
    test.com.google.protobuf.proto.ProtocolBodyOne.getDescriptor();
    test.com.google.protobuf.proto.ProtocolBodyChat.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
