// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolBodyOne.proto

package test.com.google.protobuf.proto;

public final class ProtocolBodyOne {
  private ProtocolBodyOne() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code test.com.google.protobuf.proto.Corpus}
   */
  public enum Corpus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NIL = 0;</code>
     */
    NIL(0),
    /**
     * <code>UNIVERSAL = 1;</code>
     */
    UNIVERSAL(1),
    /**
     * <code>WEB = 2;</code>
     */
    WEB(2),
    /**
     * <code>IMAGES = 3;</code>
     */
    IMAGES(3),
    /**
     * <code>LOCAL = 4;</code>
     */
    LOCAL(4),
    /**
     * <code>NEWS = 5;</code>
     */
    NEWS(5),
    /**
     * <code>PRODUCTS = 6;</code>
     */
    PRODUCTS(6),
    /**
     * <code>VIDEO = 7;</code>
     */
    VIDEO(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NIL = 0;</code>
     */
    public static final int NIL_VALUE = 0;
    /**
     * <code>UNIVERSAL = 1;</code>
     */
    public static final int UNIVERSAL_VALUE = 1;
    /**
     * <code>WEB = 2;</code>
     */
    public static final int WEB_VALUE = 2;
    /**
     * <code>IMAGES = 3;</code>
     */
    public static final int IMAGES_VALUE = 3;
    /**
     * <code>LOCAL = 4;</code>
     */
    public static final int LOCAL_VALUE = 4;
    /**
     * <code>NEWS = 5;</code>
     */
    public static final int NEWS_VALUE = 5;
    /**
     * <code>PRODUCTS = 6;</code>
     */
    public static final int PRODUCTS_VALUE = 6;
    /**
     * <code>VIDEO = 7;</code>
     */
    public static final int VIDEO_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Corpus valueOf(int value) {
      return forNumber(value);
    }

    public static Corpus forNumber(int value) {
      switch (value) {
        case 0: return NIL;
        case 1: return UNIVERSAL;
        case 2: return WEB;
        case 3: return IMAGES;
        case 4: return LOCAL;
        case 5: return NEWS;
        case 6: return PRODUCTS;
        case 7: return VIDEO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Corpus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Corpus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Corpus>() {
            public Corpus findValueByNumber(int number) {
              return Corpus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return test.com.google.protobuf.proto.ProtocolBodyOne.getDescriptor().getEnumTypes().get(0);
    }

    private static final Corpus[] VALUES = values();

    public static Corpus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Corpus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:test.com.google.protobuf.proto.Corpus)
  }

  public interface BodyOneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.com.google.protobuf.proto.BodyOne)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.test.com.google.protobuf.proto.Action action = 1;</code>
     */
    boolean hasAction();
    /**
     * <code>.test.com.google.protobuf.proto.Action action = 1;</code>
     */
    test.com.google.protobuf.proto.ProtocolBodyOne.Action getAction();
    /**
     * <code>.test.com.google.protobuf.proto.Action action = 1;</code>
     */
    test.com.google.protobuf.proto.ProtocolBodyOne.ActionOrBuilder getActionOrBuilder();

    /**
     * <code>.test.com.google.protobuf.proto.Corpus corpus = 2;</code>
     */
    int getCorpusValue();
    /**
     * <code>.test.com.google.protobuf.proto.Corpus corpus = 2;</code>
     */
    test.com.google.protobuf.proto.ProtocolBodyOne.Corpus getCorpus();

    /**
     * <code>int32 page = 3;</code>
     */
    int getPage();

    /**
     * <code>repeated float floatListTest = 4;</code>
     */
    java.util.List<java.lang.Float> getFloatListTestList();
    /**
     * <code>repeated float floatListTest = 4;</code>
     */
    int getFloatListTestCount();
    /**
     * <code>repeated float floatListTest = 4;</code>
     */
    float getFloatListTest(int index);

    /**
     * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
     */
    java.util.List<test.com.google.protobuf.proto.ProtocolBodyOne.Corpus> getCorpusListTestList();
    /**
     * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
     */
    int getCorpusListTestCount();
    /**
     * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
     */
    test.com.google.protobuf.proto.ProtocolBodyOne.Corpus getCorpusListTest(int index);
    /**
     * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
     */
    java.util.List<java.lang.Integer>
    getCorpusListTestValueList();
    /**
     * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
     */
    int getCorpusListTestValue(int index);

    /**
     * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
     */
    java.util.List<test.com.google.protobuf.proto.ProtocolBodyOne.Action> 
        getActionListTestList();
    /**
     * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
     */
    test.com.google.protobuf.proto.ProtocolBodyOne.Action getActionListTest(int index);
    /**
     * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
     */
    int getActionListTestCount();
    /**
     * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
     */
    java.util.List<? extends test.com.google.protobuf.proto.ProtocolBodyOne.ActionOrBuilder> 
        getActionListTestOrBuilderList();
    /**
     * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
     */
    test.com.google.protobuf.proto.ProtocolBodyOne.ActionOrBuilder getActionListTestOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code test.com.google.protobuf.proto.BodyOne}
   */
  public  static final class BodyOne extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.com.google.protobuf.proto.BodyOne)
      BodyOneOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BodyOne.newBuilder() to construct.
    private BodyOne(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BodyOne() {
      corpus_ = 0;
      floatListTest_ = emptyFloatList();
      corpusListTest_ = java.util.Collections.emptyList();
      actionListTest_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BodyOne(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder subBuilder = null;
              if (action_ != null) {
                subBuilder = action_.toBuilder();
              }
              action_ = input.readMessage(test.com.google.protobuf.proto.ProtocolBodyOne.Action.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(action_);
                action_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              corpus_ = rawValue;
              break;
            }
            case 24: {

              page_ = input.readInt32();
              break;
            }
            case 37: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                floatListTest_ = newFloatList();
                mutable_bitField0_ |= 0x00000008;
              }
              floatListTest_.addFloat(input.readFloat());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) != 0) && input.getBytesUntilLimit() > 0) {
                floatListTest_ = newFloatList();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                floatListTest_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                corpusListTest_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              corpusListTest_.add(rawValue);
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                  corpusListTest_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000010;
                }
                corpusListTest_.add(rawValue);
              }
              input.popLimit(oldLimit);
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) != 0)) {
                actionListTest_ = new java.util.ArrayList<test.com.google.protobuf.proto.ProtocolBodyOne.Action>();
                mutable_bitField0_ |= 0x00000020;
              }
              actionListTest_.add(
                  input.readMessage(test.com.google.protobuf.proto.ProtocolBodyOne.Action.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          floatListTest_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          corpusListTest_ = java.util.Collections.unmodifiableList(corpusListTest_);
        }
        if (((mutable_bitField0_ & 0x00000020) != 0)) {
          actionListTest_ = java.util.Collections.unmodifiableList(actionListTest_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.com.google.protobuf.proto.ProtocolBodyOne.internal_static_test_com_google_protobuf_proto_BodyOne_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.com.google.protobuf.proto.ProtocolBodyOne.internal_static_test_com_google_protobuf_proto_BodyOne_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.class, test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.Builder.class);
    }

    private int bitField0_;
    public static final int ACTION_FIELD_NUMBER = 1;
    private test.com.google.protobuf.proto.ProtocolBodyOne.Action action_;
    /**
     * <code>.test.com.google.protobuf.proto.Action action = 1;</code>
     */
    public boolean hasAction() {
      return action_ != null;
    }
    /**
     * <code>.test.com.google.protobuf.proto.Action action = 1;</code>
     */
    public test.com.google.protobuf.proto.ProtocolBodyOne.Action getAction() {
      return action_ == null ? test.com.google.protobuf.proto.ProtocolBodyOne.Action.getDefaultInstance() : action_;
    }
    /**
     * <code>.test.com.google.protobuf.proto.Action action = 1;</code>
     */
    public test.com.google.protobuf.proto.ProtocolBodyOne.ActionOrBuilder getActionOrBuilder() {
      return getAction();
    }

    public static final int CORPUS_FIELD_NUMBER = 2;
    private int corpus_;
    /**
     * <code>.test.com.google.protobuf.proto.Corpus corpus = 2;</code>
     */
    public int getCorpusValue() {
      return corpus_;
    }
    /**
     * <code>.test.com.google.protobuf.proto.Corpus corpus = 2;</code>
     */
    public test.com.google.protobuf.proto.ProtocolBodyOne.Corpus getCorpus() {
      @SuppressWarnings("deprecation")
      test.com.google.protobuf.proto.ProtocolBodyOne.Corpus result = test.com.google.protobuf.proto.ProtocolBodyOne.Corpus.valueOf(corpus_);
      return result == null ? test.com.google.protobuf.proto.ProtocolBodyOne.Corpus.UNRECOGNIZED : result;
    }

    public static final int PAGE_FIELD_NUMBER = 3;
    private int page_;
    /**
     * <code>int32 page = 3;</code>
     */
    public int getPage() {
      return page_;
    }

    public static final int FLOATLISTTEST_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.FloatList floatListTest_;
    /**
     * <code>repeated float floatListTest = 4;</code>
     */
    public java.util.List<java.lang.Float>
        getFloatListTestList() {
      return floatListTest_;
    }
    /**
     * <code>repeated float floatListTest = 4;</code>
     */
    public int getFloatListTestCount() {
      return floatListTest_.size();
    }
    /**
     * <code>repeated float floatListTest = 4;</code>
     */
    public float getFloatListTest(int index) {
      return floatListTest_.getFloat(index);
    }
    private int floatListTestMemoizedSerializedSize = -1;

    public static final int CORPUSLISTTEST_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Integer> corpusListTest_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, test.com.google.protobuf.proto.ProtocolBodyOne.Corpus> corpusListTest_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, test.com.google.protobuf.proto.ProtocolBodyOne.Corpus>() {
              public test.com.google.protobuf.proto.ProtocolBodyOne.Corpus convert(java.lang.Integer from) {
                @SuppressWarnings("deprecation")
                test.com.google.protobuf.proto.ProtocolBodyOne.Corpus result = test.com.google.protobuf.proto.ProtocolBodyOne.Corpus.valueOf(from);
                return result == null ? test.com.google.protobuf.proto.ProtocolBodyOne.Corpus.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
     */
    public java.util.List<test.com.google.protobuf.proto.ProtocolBodyOne.Corpus> getCorpusListTestList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, test.com.google.protobuf.proto.ProtocolBodyOne.Corpus>(corpusListTest_, corpusListTest_converter_);
    }
    /**
     * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
     */
    public int getCorpusListTestCount() {
      return corpusListTest_.size();
    }
    /**
     * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
     */
    public test.com.google.protobuf.proto.ProtocolBodyOne.Corpus getCorpusListTest(int index) {
      return corpusListTest_converter_.convert(corpusListTest_.get(index));
    }
    /**
     * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
     */
    public java.util.List<java.lang.Integer>
    getCorpusListTestValueList() {
      return corpusListTest_;
    }
    /**
     * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
     */
    public int getCorpusListTestValue(int index) {
      return corpusListTest_.get(index);
    }
    private int corpusListTestMemoizedSerializedSize;

    public static final int ACTIONLISTTEST_FIELD_NUMBER = 6;
    private java.util.List<test.com.google.protobuf.proto.ProtocolBodyOne.Action> actionListTest_;
    /**
     * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
     */
    public java.util.List<test.com.google.protobuf.proto.ProtocolBodyOne.Action> getActionListTestList() {
      return actionListTest_;
    }
    /**
     * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
     */
    public java.util.List<? extends test.com.google.protobuf.proto.ProtocolBodyOne.ActionOrBuilder> 
        getActionListTestOrBuilderList() {
      return actionListTest_;
    }
    /**
     * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
     */
    public int getActionListTestCount() {
      return actionListTest_.size();
    }
    /**
     * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
     */
    public test.com.google.protobuf.proto.ProtocolBodyOne.Action getActionListTest(int index) {
      return actionListTest_.get(index);
    }
    /**
     * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
     */
    public test.com.google.protobuf.proto.ProtocolBodyOne.ActionOrBuilder getActionListTestOrBuilder(
        int index) {
      return actionListTest_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (action_ != null) {
        output.writeMessage(1, getAction());
      }
      if (corpus_ != test.com.google.protobuf.proto.ProtocolBodyOne.Corpus.NIL.getNumber()) {
        output.writeEnum(2, corpus_);
      }
      if (page_ != 0) {
        output.writeInt32(3, page_);
      }
      if (getFloatListTestList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(floatListTestMemoizedSerializedSize);
      }
      for (int i = 0; i < floatListTest_.size(); i++) {
        output.writeFloatNoTag(floatListTest_.getFloat(i));
      }
      if (getCorpusListTestList().size() > 0) {
        output.writeUInt32NoTag(42);
        output.writeUInt32NoTag(corpusListTestMemoizedSerializedSize);
      }
      for (int i = 0; i < corpusListTest_.size(); i++) {
        output.writeEnumNoTag(corpusListTest_.get(i));
      }
      for (int i = 0; i < actionListTest_.size(); i++) {
        output.writeMessage(6, actionListTest_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (action_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getAction());
      }
      if (corpus_ != test.com.google.protobuf.proto.ProtocolBodyOne.Corpus.NIL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, corpus_);
      }
      if (page_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, page_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getFloatListTestList().size();
        size += dataSize;
        if (!getFloatListTestList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        floatListTestMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < corpusListTest_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(corpusListTest_.get(i));
        }
        size += dataSize;
        if (!getCorpusListTestList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }corpusListTestMemoizedSerializedSize = dataSize;
      }
      for (int i = 0; i < actionListTest_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, actionListTest_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne)) {
        return super.equals(obj);
      }
      test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne other = (test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne) obj;

      if (hasAction() != other.hasAction()) return false;
      if (hasAction()) {
        if (!getAction()
            .equals(other.getAction())) return false;
      }
      if (corpus_ != other.corpus_) return false;
      if (getPage()
          != other.getPage()) return false;
      if (!getFloatListTestList()
          .equals(other.getFloatListTestList())) return false;
      if (!corpusListTest_.equals(other.corpusListTest_)) return false;
      if (!getActionListTestList()
          .equals(other.getActionListTestList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAction()) {
        hash = (37 * hash) + ACTION_FIELD_NUMBER;
        hash = (53 * hash) + getAction().hashCode();
      }
      hash = (37 * hash) + CORPUS_FIELD_NUMBER;
      hash = (53 * hash) + corpus_;
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage();
      if (getFloatListTestCount() > 0) {
        hash = (37 * hash) + FLOATLISTTEST_FIELD_NUMBER;
        hash = (53 * hash) + getFloatListTestList().hashCode();
      }
      if (getCorpusListTestCount() > 0) {
        hash = (37 * hash) + CORPUSLISTTEST_FIELD_NUMBER;
        hash = (53 * hash) + corpusListTest_.hashCode();
      }
      if (getActionListTestCount() > 0) {
        hash = (37 * hash) + ACTIONLISTTEST_FIELD_NUMBER;
        hash = (53 * hash) + getActionListTestList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.com.google.protobuf.proto.BodyOne}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.com.google.protobuf.proto.BodyOne)
        test.com.google.protobuf.proto.ProtocolBodyOne.BodyOneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.com.google.protobuf.proto.ProtocolBodyOne.internal_static_test_com_google_protobuf_proto_BodyOne_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.com.google.protobuf.proto.ProtocolBodyOne.internal_static_test_com_google_protobuf_proto_BodyOne_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.class, test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.Builder.class);
      }

      // Construct using test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getActionListTestFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (actionBuilder_ == null) {
          action_ = null;
        } else {
          action_ = null;
          actionBuilder_ = null;
        }
        corpus_ = 0;

        page_ = 0;

        floatListTest_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000008);
        corpusListTest_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        if (actionListTestBuilder_ == null) {
          actionListTest_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          actionListTestBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.com.google.protobuf.proto.ProtocolBodyOne.internal_static_test_com_google_protobuf_proto_BodyOne_descriptor;
      }

      @java.lang.Override
      public test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne getDefaultInstanceForType() {
        return test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.getDefaultInstance();
      }

      @java.lang.Override
      public test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne build() {
        test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne buildPartial() {
        test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne result = new test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (actionBuilder_ == null) {
          result.action_ = action_;
        } else {
          result.action_ = actionBuilder_.build();
        }
        result.corpus_ = corpus_;
        result.page_ = page_;
        if (((bitField0_ & 0x00000008) != 0)) {
          floatListTest_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.floatListTest_ = floatListTest_;
        if (((bitField0_ & 0x00000010) != 0)) {
          corpusListTest_ = java.util.Collections.unmodifiableList(corpusListTest_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.corpusListTest_ = corpusListTest_;
        if (actionListTestBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0)) {
            actionListTest_ = java.util.Collections.unmodifiableList(actionListTest_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.actionListTest_ = actionListTest_;
        } else {
          result.actionListTest_ = actionListTestBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne) {
          return mergeFrom((test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne other) {
        if (other == test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne.getDefaultInstance()) return this;
        if (other.hasAction()) {
          mergeAction(other.getAction());
        }
        if (other.corpus_ != 0) {
          setCorpusValue(other.getCorpusValue());
        }
        if (other.getPage() != 0) {
          setPage(other.getPage());
        }
        if (!other.floatListTest_.isEmpty()) {
          if (floatListTest_.isEmpty()) {
            floatListTest_ = other.floatListTest_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureFloatListTestIsMutable();
            floatListTest_.addAll(other.floatListTest_);
          }
          onChanged();
        }
        if (!other.corpusListTest_.isEmpty()) {
          if (corpusListTest_.isEmpty()) {
            corpusListTest_ = other.corpusListTest_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureCorpusListTestIsMutable();
            corpusListTest_.addAll(other.corpusListTest_);
          }
          onChanged();
        }
        if (actionListTestBuilder_ == null) {
          if (!other.actionListTest_.isEmpty()) {
            if (actionListTest_.isEmpty()) {
              actionListTest_ = other.actionListTest_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureActionListTestIsMutable();
              actionListTest_.addAll(other.actionListTest_);
            }
            onChanged();
          }
        } else {
          if (!other.actionListTest_.isEmpty()) {
            if (actionListTestBuilder_.isEmpty()) {
              actionListTestBuilder_.dispose();
              actionListTestBuilder_ = null;
              actionListTest_ = other.actionListTest_;
              bitField0_ = (bitField0_ & ~0x00000020);
              actionListTestBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getActionListTestFieldBuilder() : null;
            } else {
              actionListTestBuilder_.addAllMessages(other.actionListTest_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private test.com.google.protobuf.proto.ProtocolBodyOne.Action action_;
      private com.google.protobuf.SingleFieldBuilderV3<
          test.com.google.protobuf.proto.ProtocolBodyOne.Action, test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder, test.com.google.protobuf.proto.ProtocolBodyOne.ActionOrBuilder> actionBuilder_;
      /**
       * <code>.test.com.google.protobuf.proto.Action action = 1;</code>
       */
      public boolean hasAction() {
        return actionBuilder_ != null || action_ != null;
      }
      /**
       * <code>.test.com.google.protobuf.proto.Action action = 1;</code>
       */
      public test.com.google.protobuf.proto.ProtocolBodyOne.Action getAction() {
        if (actionBuilder_ == null) {
          return action_ == null ? test.com.google.protobuf.proto.ProtocolBodyOne.Action.getDefaultInstance() : action_;
        } else {
          return actionBuilder_.getMessage();
        }
      }
      /**
       * <code>.test.com.google.protobuf.proto.Action action = 1;</code>
       */
      public Builder setAction(test.com.google.protobuf.proto.ProtocolBodyOne.Action value) {
        if (actionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          action_ = value;
          onChanged();
        } else {
          actionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.Action action = 1;</code>
       */
      public Builder setAction(
          test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder builderForValue) {
        if (actionBuilder_ == null) {
          action_ = builderForValue.build();
          onChanged();
        } else {
          actionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.Action action = 1;</code>
       */
      public Builder mergeAction(test.com.google.protobuf.proto.ProtocolBodyOne.Action value) {
        if (actionBuilder_ == null) {
          if (action_ != null) {
            action_ =
              test.com.google.protobuf.proto.ProtocolBodyOne.Action.newBuilder(action_).mergeFrom(value).buildPartial();
          } else {
            action_ = value;
          }
          onChanged();
        } else {
          actionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.Action action = 1;</code>
       */
      public Builder clearAction() {
        if (actionBuilder_ == null) {
          action_ = null;
          onChanged();
        } else {
          action_ = null;
          actionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.Action action = 1;</code>
       */
      public test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder getActionBuilder() {
        
        onChanged();
        return getActionFieldBuilder().getBuilder();
      }
      /**
       * <code>.test.com.google.protobuf.proto.Action action = 1;</code>
       */
      public test.com.google.protobuf.proto.ProtocolBodyOne.ActionOrBuilder getActionOrBuilder() {
        if (actionBuilder_ != null) {
          return actionBuilder_.getMessageOrBuilder();
        } else {
          return action_ == null ?
              test.com.google.protobuf.proto.ProtocolBodyOne.Action.getDefaultInstance() : action_;
        }
      }
      /**
       * <code>.test.com.google.protobuf.proto.Action action = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          test.com.google.protobuf.proto.ProtocolBodyOne.Action, test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder, test.com.google.protobuf.proto.ProtocolBodyOne.ActionOrBuilder> 
          getActionFieldBuilder() {
        if (actionBuilder_ == null) {
          actionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              test.com.google.protobuf.proto.ProtocolBodyOne.Action, test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder, test.com.google.protobuf.proto.ProtocolBodyOne.ActionOrBuilder>(
                  getAction(),
                  getParentForChildren(),
                  isClean());
          action_ = null;
        }
        return actionBuilder_;
      }

      private int corpus_ = 0;
      /**
       * <code>.test.com.google.protobuf.proto.Corpus corpus = 2;</code>
       */
      public int getCorpusValue() {
        return corpus_;
      }
      /**
       * <code>.test.com.google.protobuf.proto.Corpus corpus = 2;</code>
       */
      public Builder setCorpusValue(int value) {
        corpus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.Corpus corpus = 2;</code>
       */
      public test.com.google.protobuf.proto.ProtocolBodyOne.Corpus getCorpus() {
        @SuppressWarnings("deprecation")
        test.com.google.protobuf.proto.ProtocolBodyOne.Corpus result = test.com.google.protobuf.proto.ProtocolBodyOne.Corpus.valueOf(corpus_);
        return result == null ? test.com.google.protobuf.proto.ProtocolBodyOne.Corpus.UNRECOGNIZED : result;
      }
      /**
       * <code>.test.com.google.protobuf.proto.Corpus corpus = 2;</code>
       */
      public Builder setCorpus(test.com.google.protobuf.proto.ProtocolBodyOne.Corpus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        corpus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.test.com.google.protobuf.proto.Corpus corpus = 2;</code>
       */
      public Builder clearCorpus() {
        
        corpus_ = 0;
        onChanged();
        return this;
      }

      private int page_ ;
      /**
       * <code>int32 page = 3;</code>
       */
      public int getPage() {
        return page_;
      }
      /**
       * <code>int32 page = 3;</code>
       */
      public Builder setPage(int value) {
        
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 page = 3;</code>
       */
      public Builder clearPage() {
        
        page_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.FloatList floatListTest_ = emptyFloatList();
      private void ensureFloatListTestIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          floatListTest_ = mutableCopy(floatListTest_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated float floatListTest = 4;</code>
       */
      public java.util.List<java.lang.Float>
          getFloatListTestList() {
        return ((bitField0_ & 0x00000008) != 0) ?
                 java.util.Collections.unmodifiableList(floatListTest_) : floatListTest_;
      }
      /**
       * <code>repeated float floatListTest = 4;</code>
       */
      public int getFloatListTestCount() {
        return floatListTest_.size();
      }
      /**
       * <code>repeated float floatListTest = 4;</code>
       */
      public float getFloatListTest(int index) {
        return floatListTest_.getFloat(index);
      }
      /**
       * <code>repeated float floatListTest = 4;</code>
       */
      public Builder setFloatListTest(
          int index, float value) {
        ensureFloatListTestIsMutable();
        floatListTest_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float floatListTest = 4;</code>
       */
      public Builder addFloatListTest(float value) {
        ensureFloatListTestIsMutable();
        floatListTest_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float floatListTest = 4;</code>
       */
      public Builder addAllFloatListTest(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureFloatListTestIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, floatListTest_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float floatListTest = 4;</code>
       */
      public Builder clearFloatListTest() {
        floatListTest_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> corpusListTest_ =
        java.util.Collections.emptyList();
      private void ensureCorpusListTestIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          corpusListTest_ = new java.util.ArrayList<java.lang.Integer>(corpusListTest_);
          bitField0_ |= 0x00000010;
        }
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
       */
      public java.util.List<test.com.google.protobuf.proto.ProtocolBodyOne.Corpus> getCorpusListTestList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, test.com.google.protobuf.proto.ProtocolBodyOne.Corpus>(corpusListTest_, corpusListTest_converter_);
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
       */
      public int getCorpusListTestCount() {
        return corpusListTest_.size();
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
       */
      public test.com.google.protobuf.proto.ProtocolBodyOne.Corpus getCorpusListTest(int index) {
        return corpusListTest_converter_.convert(corpusListTest_.get(index));
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
       */
      public Builder setCorpusListTest(
          int index, test.com.google.protobuf.proto.ProtocolBodyOne.Corpus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCorpusListTestIsMutable();
        corpusListTest_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
       */
      public Builder addCorpusListTest(test.com.google.protobuf.proto.ProtocolBodyOne.Corpus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCorpusListTestIsMutable();
        corpusListTest_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
       */
      public Builder addAllCorpusListTest(
          java.lang.Iterable<? extends test.com.google.protobuf.proto.ProtocolBodyOne.Corpus> values) {
        ensureCorpusListTestIsMutable();
        for (test.com.google.protobuf.proto.ProtocolBodyOne.Corpus value : values) {
          corpusListTest_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
       */
      public Builder clearCorpusListTest() {
        corpusListTest_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
       */
      public java.util.List<java.lang.Integer>
      getCorpusListTestValueList() {
        return java.util.Collections.unmodifiableList(corpusListTest_);
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
       */
      public int getCorpusListTestValue(int index) {
        return corpusListTest_.get(index);
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
       */
      public Builder setCorpusListTestValue(
          int index, int value) {
        ensureCorpusListTestIsMutable();
        corpusListTest_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
       */
      public Builder addCorpusListTestValue(int value) {
        ensureCorpusListTestIsMutable();
        corpusListTest_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Corpus corpusListTest = 5;</code>
       */
      public Builder addAllCorpusListTestValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureCorpusListTestIsMutable();
        for (int value : values) {
          corpusListTest_.add(value);
        }
        onChanged();
        return this;
      }

      private java.util.List<test.com.google.protobuf.proto.ProtocolBodyOne.Action> actionListTest_ =
        java.util.Collections.emptyList();
      private void ensureActionListTestIsMutable() {
        if (!((bitField0_ & 0x00000020) != 0)) {
          actionListTest_ = new java.util.ArrayList<test.com.google.protobuf.proto.ProtocolBodyOne.Action>(actionListTest_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          test.com.google.protobuf.proto.ProtocolBodyOne.Action, test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder, test.com.google.protobuf.proto.ProtocolBodyOne.ActionOrBuilder> actionListTestBuilder_;

      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public java.util.List<test.com.google.protobuf.proto.ProtocolBodyOne.Action> getActionListTestList() {
        if (actionListTestBuilder_ == null) {
          return java.util.Collections.unmodifiableList(actionListTest_);
        } else {
          return actionListTestBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public int getActionListTestCount() {
        if (actionListTestBuilder_ == null) {
          return actionListTest_.size();
        } else {
          return actionListTestBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public test.com.google.protobuf.proto.ProtocolBodyOne.Action getActionListTest(int index) {
        if (actionListTestBuilder_ == null) {
          return actionListTest_.get(index);
        } else {
          return actionListTestBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public Builder setActionListTest(
          int index, test.com.google.protobuf.proto.ProtocolBodyOne.Action value) {
        if (actionListTestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActionListTestIsMutable();
          actionListTest_.set(index, value);
          onChanged();
        } else {
          actionListTestBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public Builder setActionListTest(
          int index, test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder builderForValue) {
        if (actionListTestBuilder_ == null) {
          ensureActionListTestIsMutable();
          actionListTest_.set(index, builderForValue.build());
          onChanged();
        } else {
          actionListTestBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public Builder addActionListTest(test.com.google.protobuf.proto.ProtocolBodyOne.Action value) {
        if (actionListTestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActionListTestIsMutable();
          actionListTest_.add(value);
          onChanged();
        } else {
          actionListTestBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public Builder addActionListTest(
          int index, test.com.google.protobuf.proto.ProtocolBodyOne.Action value) {
        if (actionListTestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActionListTestIsMutable();
          actionListTest_.add(index, value);
          onChanged();
        } else {
          actionListTestBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public Builder addActionListTest(
          test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder builderForValue) {
        if (actionListTestBuilder_ == null) {
          ensureActionListTestIsMutable();
          actionListTest_.add(builderForValue.build());
          onChanged();
        } else {
          actionListTestBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public Builder addActionListTest(
          int index, test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder builderForValue) {
        if (actionListTestBuilder_ == null) {
          ensureActionListTestIsMutable();
          actionListTest_.add(index, builderForValue.build());
          onChanged();
        } else {
          actionListTestBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public Builder addAllActionListTest(
          java.lang.Iterable<? extends test.com.google.protobuf.proto.ProtocolBodyOne.Action> values) {
        if (actionListTestBuilder_ == null) {
          ensureActionListTestIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, actionListTest_);
          onChanged();
        } else {
          actionListTestBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public Builder clearActionListTest() {
        if (actionListTestBuilder_ == null) {
          actionListTest_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          actionListTestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public Builder removeActionListTest(int index) {
        if (actionListTestBuilder_ == null) {
          ensureActionListTestIsMutable();
          actionListTest_.remove(index);
          onChanged();
        } else {
          actionListTestBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder getActionListTestBuilder(
          int index) {
        return getActionListTestFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public test.com.google.protobuf.proto.ProtocolBodyOne.ActionOrBuilder getActionListTestOrBuilder(
          int index) {
        if (actionListTestBuilder_ == null) {
          return actionListTest_.get(index);  } else {
          return actionListTestBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public java.util.List<? extends test.com.google.protobuf.proto.ProtocolBodyOne.ActionOrBuilder> 
           getActionListTestOrBuilderList() {
        if (actionListTestBuilder_ != null) {
          return actionListTestBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(actionListTest_);
        }
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder addActionListTestBuilder() {
        return getActionListTestFieldBuilder().addBuilder(
            test.com.google.protobuf.proto.ProtocolBodyOne.Action.getDefaultInstance());
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder addActionListTestBuilder(
          int index) {
        return getActionListTestFieldBuilder().addBuilder(
            index, test.com.google.protobuf.proto.ProtocolBodyOne.Action.getDefaultInstance());
      }
      /**
       * <code>repeated .test.com.google.protobuf.proto.Action actionListTest = 6;</code>
       */
      public java.util.List<test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder> 
           getActionListTestBuilderList() {
        return getActionListTestFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          test.com.google.protobuf.proto.ProtocolBodyOne.Action, test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder, test.com.google.protobuf.proto.ProtocolBodyOne.ActionOrBuilder> 
          getActionListTestFieldBuilder() {
        if (actionListTestBuilder_ == null) {
          actionListTestBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              test.com.google.protobuf.proto.ProtocolBodyOne.Action, test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder, test.com.google.protobuf.proto.ProtocolBodyOne.ActionOrBuilder>(
                  actionListTest_,
                  ((bitField0_ & 0x00000020) != 0),
                  getParentForChildren(),
                  isClean());
          actionListTest_ = null;
        }
        return actionListTestBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.com.google.protobuf.proto.BodyOne)
    }

    // @@protoc_insertion_point(class_scope:test.com.google.protobuf.proto.BodyOne)
    private static final test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne();
    }

    public static test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BodyOne>
        PARSER = new com.google.protobuf.AbstractParser<BodyOne>() {
      @java.lang.Override
      public BodyOne parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BodyOne(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BodyOne> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BodyOne> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.com.google.protobuf.proto.ProtocolBodyOne.BodyOne getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.com.google.protobuf.proto.Action)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     * type类型：
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    int getType();
  }
  /**
   * Protobuf type {@code test.com.google.protobuf.proto.Action}
   */
  public  static final class Action extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.com.google.protobuf.proto.Action)
      ActionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Action.newBuilder() to construct.
    private Action(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Action() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Action(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              type_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.com.google.protobuf.proto.ProtocolBodyOne.internal_static_test_com_google_protobuf_proto_Action_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.com.google.protobuf.proto.ProtocolBodyOne.internal_static_test_com_google_protobuf_proto_Action_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.com.google.protobuf.proto.ProtocolBodyOne.Action.class, test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     **
     * type类型：
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.com.google.protobuf.proto.ProtocolBodyOne.Action)) {
        return super.equals(obj);
      }
      test.com.google.protobuf.proto.ProtocolBodyOne.Action other = (test.com.google.protobuf.proto.ProtocolBodyOne.Action) obj;

      if (getType()
          != other.getType()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.com.google.protobuf.proto.ProtocolBodyOne.Action parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.Action parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.Action parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.Action parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.Action parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.Action parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.Action parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.Action parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.Action parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.Action parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.Action parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyOne.Action parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.com.google.protobuf.proto.ProtocolBodyOne.Action prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.com.google.protobuf.proto.Action}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.com.google.protobuf.proto.Action)
        test.com.google.protobuf.proto.ProtocolBodyOne.ActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.com.google.protobuf.proto.ProtocolBodyOne.internal_static_test_com_google_protobuf_proto_Action_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.com.google.protobuf.proto.ProtocolBodyOne.internal_static_test_com_google_protobuf_proto_Action_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.com.google.protobuf.proto.ProtocolBodyOne.Action.class, test.com.google.protobuf.proto.ProtocolBodyOne.Action.Builder.class);
      }

      // Construct using test.com.google.protobuf.proto.ProtocolBodyOne.Action.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.com.google.protobuf.proto.ProtocolBodyOne.internal_static_test_com_google_protobuf_proto_Action_descriptor;
      }

      @java.lang.Override
      public test.com.google.protobuf.proto.ProtocolBodyOne.Action getDefaultInstanceForType() {
        return test.com.google.protobuf.proto.ProtocolBodyOne.Action.getDefaultInstance();
      }

      @java.lang.Override
      public test.com.google.protobuf.proto.ProtocolBodyOne.Action build() {
        test.com.google.protobuf.proto.ProtocolBodyOne.Action result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.com.google.protobuf.proto.ProtocolBodyOne.Action buildPartial() {
        test.com.google.protobuf.proto.ProtocolBodyOne.Action result = new test.com.google.protobuf.proto.ProtocolBodyOne.Action(this);
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.com.google.protobuf.proto.ProtocolBodyOne.Action) {
          return mergeFrom((test.com.google.protobuf.proto.ProtocolBodyOne.Action)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.com.google.protobuf.proto.ProtocolBodyOne.Action other) {
        if (other == test.com.google.protobuf.proto.ProtocolBodyOne.Action.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.com.google.protobuf.proto.ProtocolBodyOne.Action parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.com.google.protobuf.proto.ProtocolBodyOne.Action) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       **
       * type类型：
       * </pre>
       *
       * <code>int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       **
       * type类型：
       * </pre>
       *
       * <code>int32 type = 1;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * type类型：
       * </pre>
       *
       * <code>int32 type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.com.google.protobuf.proto.Action)
    }

    // @@protoc_insertion_point(class_scope:test.com.google.protobuf.proto.Action)
    private static final test.com.google.protobuf.proto.ProtocolBodyOne.Action DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.com.google.protobuf.proto.ProtocolBodyOne.Action();
    }

    public static test.com.google.protobuf.proto.ProtocolBodyOne.Action getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Action>
        PARSER = new com.google.protobuf.AbstractParser<Action>() {
      @java.lang.Override
      public Action parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Action(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Action> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Action> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.com.google.protobuf.proto.ProtocolBodyOne.Action getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_com_google_protobuf_proto_BodyOne_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_com_google_protobuf_proto_BodyOne_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_com_google_protobuf_proto_Action_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_com_google_protobuf_proto_Action_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ProtocolBodyOne.proto\022\036test.com.google" +
      ".protobuf.proto\"\236\002\n\007BodyOne\0226\n\006action\030\001 " +
      "\001(\0132&.test.com.google.protobuf.proto.Act" +
      "ion\0226\n\006corpus\030\002 \001(\0162&.test.com.google.pr" +
      "otobuf.proto.Corpus\022\014\n\004page\030\003 \001(\005\022\025\n\rflo" +
      "atListTest\030\004 \003(\002\022>\n\016corpusListTest\030\005 \003(\016" +
      "2&.test.com.google.protobuf.proto.Corpus" +
      "\022>\n\016actionListTest\030\006 \003(\0132&.test.com.goog" +
      "le.protobuf.proto.Action\"\026\n\006Action\022\014\n\004ty" +
      "pe\030\001 \001(\005*c\n\006Corpus\022\007\n\003NIL\020\000\022\r\n\tUNIVERSAL" +
      "\020\001\022\007\n\003WEB\020\002\022\n\n\006IMAGES\020\003\022\t\n\005LOCAL\020\004\022\010\n\004NE" +
      "WS\020\005\022\014\n\010PRODUCTS\020\006\022\t\n\005VIDEO\020\007B\021B\017Protoco" +
      "lBodyOneb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_test_com_google_protobuf_proto_BodyOne_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_com_google_protobuf_proto_BodyOne_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_com_google_protobuf_proto_BodyOne_descriptor,
        new java.lang.String[] { "Action", "Corpus", "Page", "FloatListTest", "CorpusListTest", "ActionListTest", });
    internal_static_test_com_google_protobuf_proto_Action_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_test_com_google_protobuf_proto_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_com_google_protobuf_proto_Action_descriptor,
        new java.lang.String[] { "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
