// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolBodyChat.proto

package test.com.google.protobuf.proto;

public final class ProtocolBodyChat {
  private ProtocolBodyChat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BodyChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.com.google.protobuf.proto.BodyChat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 from = 1;</code>
     */
    int getFrom();

    /**
     * <code>int32 chatType = 2;</code>
     */
    int getChatType();

    /**
     * <code>int32 roomId = 3;</code>
     */
    int getRoomId();

    /**
     * <code>repeated int32 to = 4;</code>
     */
    java.util.List<java.lang.Integer> getToList();
    /**
     * <code>repeated int32 to = 4;</code>
     */
    int getToCount();
    /**
     * <code>repeated int32 to = 4;</code>
     */
    int getTo(int index);

    /**
     * <code>repeated string text = 5;</code>
     */
    java.util.List<java.lang.String>
        getTextList();
    /**
     * <code>repeated string text = 5;</code>
     */
    int getTextCount();
    /**
     * <code>repeated string text = 5;</code>
     */
    java.lang.String getText(int index);
    /**
     * <code>repeated string text = 5;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes(int index);
  }
  /**
   * Protobuf type {@code test.com.google.protobuf.proto.BodyChat}
   */
  public  static final class BodyChat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.com.google.protobuf.proto.BodyChat)
      BodyChatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BodyChat.newBuilder() to construct.
    private BodyChat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BodyChat() {
      to_ = emptyIntList();
      text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BodyChat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              from_ = input.readInt32();
              break;
            }
            case 16: {

              chatType_ = input.readInt32();
              break;
            }
            case 24: {

              roomId_ = input.readInt32();
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                to_ = newIntList();
                mutable_bitField0_ |= 0x00000008;
              }
              to_.addInt(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) != 0) && input.getBytesUntilLimit() > 0) {
                to_ = newIntList();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                to_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                text_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              text_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          to_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          text_ = text_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.com.google.protobuf.proto.ProtocolBodyChat.internal_static_test_com_google_protobuf_proto_BodyChat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.com.google.protobuf.proto.ProtocolBodyChat.internal_static_test_com_google_protobuf_proto_BodyChat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.class, test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.Builder.class);
    }

    private int bitField0_;
    public static final int FROM_FIELD_NUMBER = 1;
    private int from_;
    /**
     * <code>int32 from = 1;</code>
     */
    public int getFrom() {
      return from_;
    }

    public static final int CHATTYPE_FIELD_NUMBER = 2;
    private int chatType_;
    /**
     * <code>int32 chatType = 2;</code>
     */
    public int getChatType() {
      return chatType_;
    }

    public static final int ROOMID_FIELD_NUMBER = 3;
    private int roomId_;
    /**
     * <code>int32 roomId = 3;</code>
     */
    public int getRoomId() {
      return roomId_;
    }

    public static final int TO_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.IntList to_;
    /**
     * <code>repeated int32 to = 4;</code>
     */
    public java.util.List<java.lang.Integer>
        getToList() {
      return to_;
    }
    /**
     * <code>repeated int32 to = 4;</code>
     */
    public int getToCount() {
      return to_.size();
    }
    /**
     * <code>repeated int32 to = 4;</code>
     */
    public int getTo(int index) {
      return to_.getInt(index);
    }
    private int toMemoizedSerializedSize = -1;

    public static final int TEXT_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList text_;
    /**
     * <code>repeated string text = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTextList() {
      return text_;
    }
    /**
     * <code>repeated string text = 5;</code>
     */
    public int getTextCount() {
      return text_.size();
    }
    /**
     * <code>repeated string text = 5;</code>
     */
    public java.lang.String getText(int index) {
      return text_.get(index);
    }
    /**
     * <code>repeated string text = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes(int index) {
      return text_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (from_ != 0) {
        output.writeInt32(1, from_);
      }
      if (chatType_ != 0) {
        output.writeInt32(2, chatType_);
      }
      if (roomId_ != 0) {
        output.writeInt32(3, roomId_);
      }
      if (getToList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(toMemoizedSerializedSize);
      }
      for (int i = 0; i < to_.size(); i++) {
        output.writeInt32NoTag(to_.getInt(i));
      }
      for (int i = 0; i < text_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, text_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (from_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, from_);
      }
      if (chatType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, chatType_);
      }
      if (roomId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, roomId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < to_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(to_.getInt(i));
        }
        size += dataSize;
        if (!getToList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        toMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < text_.size(); i++) {
          dataSize += computeStringSizeNoTag(text_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTextList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat)) {
        return super.equals(obj);
      }
      test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat other = (test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat) obj;

      if (getFrom()
          != other.getFrom()) return false;
      if (getChatType()
          != other.getChatType()) return false;
      if (getRoomId()
          != other.getRoomId()) return false;
      if (!getToList()
          .equals(other.getToList())) return false;
      if (!getTextList()
          .equals(other.getTextList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom();
      hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getChatType();
      hash = (37 * hash) + ROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomId();
      if (getToCount() > 0) {
        hash = (37 * hash) + TO_FIELD_NUMBER;
        hash = (53 * hash) + getToList().hashCode();
      }
      if (getTextCount() > 0) {
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getTextList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.com.google.protobuf.proto.BodyChat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.com.google.protobuf.proto.BodyChat)
        test.com.google.protobuf.proto.ProtocolBodyChat.BodyChatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.com.google.protobuf.proto.ProtocolBodyChat.internal_static_test_com_google_protobuf_proto_BodyChat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.com.google.protobuf.proto.ProtocolBodyChat.internal_static_test_com_google_protobuf_proto_BodyChat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.class, test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.Builder.class);
      }

      // Construct using test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        from_ = 0;

        chatType_ = 0;

        roomId_ = 0;

        to_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.com.google.protobuf.proto.ProtocolBodyChat.internal_static_test_com_google_protobuf_proto_BodyChat_descriptor;
      }

      @java.lang.Override
      public test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat getDefaultInstanceForType() {
        return test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.getDefaultInstance();
      }

      @java.lang.Override
      public test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat build() {
        test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat buildPartial() {
        test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat result = new test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.from_ = from_;
        result.chatType_ = chatType_;
        result.roomId_ = roomId_;
        if (((bitField0_ & 0x00000008) != 0)) {
          to_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.to_ = to_;
        if (((bitField0_ & 0x00000010) != 0)) {
          text_ = text_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat) {
          return mergeFrom((test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat other) {
        if (other == test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat.getDefaultInstance()) return this;
        if (other.getFrom() != 0) {
          setFrom(other.getFrom());
        }
        if (other.getChatType() != 0) {
          setChatType(other.getChatType());
        }
        if (other.getRoomId() != 0) {
          setRoomId(other.getRoomId());
        }
        if (!other.to_.isEmpty()) {
          if (to_.isEmpty()) {
            to_ = other.to_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureToIsMutable();
            to_.addAll(other.to_);
          }
          onChanged();
        }
        if (!other.text_.isEmpty()) {
          if (text_.isEmpty()) {
            text_ = other.text_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureTextIsMutable();
            text_.addAll(other.text_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int from_ ;
      /**
       * <code>int32 from = 1;</code>
       */
      public int getFrom() {
        return from_;
      }
      /**
       * <code>int32 from = 1;</code>
       */
      public Builder setFrom(int value) {
        
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 from = 1;</code>
       */
      public Builder clearFrom() {
        
        from_ = 0;
        onChanged();
        return this;
      }

      private int chatType_ ;
      /**
       * <code>int32 chatType = 2;</code>
       */
      public int getChatType() {
        return chatType_;
      }
      /**
       * <code>int32 chatType = 2;</code>
       */
      public Builder setChatType(int value) {
        
        chatType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chatType = 2;</code>
       */
      public Builder clearChatType() {
        
        chatType_ = 0;
        onChanged();
        return this;
      }

      private int roomId_ ;
      /**
       * <code>int32 roomId = 3;</code>
       */
      public int getRoomId() {
        return roomId_;
      }
      /**
       * <code>int32 roomId = 3;</code>
       */
      public Builder setRoomId(int value) {
        
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 roomId = 3;</code>
       */
      public Builder clearRoomId() {
        
        roomId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList to_ = emptyIntList();
      private void ensureToIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          to_ = mutableCopy(to_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 to = 4;</code>
       */
      public java.util.List<java.lang.Integer>
          getToList() {
        return ((bitField0_ & 0x00000008) != 0) ?
                 java.util.Collections.unmodifiableList(to_) : to_;
      }
      /**
       * <code>repeated int32 to = 4;</code>
       */
      public int getToCount() {
        return to_.size();
      }
      /**
       * <code>repeated int32 to = 4;</code>
       */
      public int getTo(int index) {
        return to_.getInt(index);
      }
      /**
       * <code>repeated int32 to = 4;</code>
       */
      public Builder setTo(
          int index, int value) {
        ensureToIsMutable();
        to_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 to = 4;</code>
       */
      public Builder addTo(int value) {
        ensureToIsMutable();
        to_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 to = 4;</code>
       */
      public Builder addAllTo(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureToIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, to_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 to = 4;</code>
       */
      public Builder clearTo() {
        to_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTextIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          text_ = new com.google.protobuf.LazyStringArrayList(text_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string text = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTextList() {
        return text_.getUnmodifiableView();
      }
      /**
       * <code>repeated string text = 5;</code>
       */
      public int getTextCount() {
        return text_.size();
      }
      /**
       * <code>repeated string text = 5;</code>
       */
      public java.lang.String getText(int index) {
        return text_.get(index);
      }
      /**
       * <code>repeated string text = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes(int index) {
        return text_.getByteString(index);
      }
      /**
       * <code>repeated string text = 5;</code>
       */
      public Builder setText(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTextIsMutable();
        text_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 5;</code>
       */
      public Builder addText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTextIsMutable();
        text_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 5;</code>
       */
      public Builder addAllText(
          java.lang.Iterable<java.lang.String> values) {
        ensureTextIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, text_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 5;</code>
       */
      public Builder clearText() {
        text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 5;</code>
       */
      public Builder addTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTextIsMutable();
        text_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.com.google.protobuf.proto.BodyChat)
    }

    // @@protoc_insertion_point(class_scope:test.com.google.protobuf.proto.BodyChat)
    private static final test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat();
    }

    public static test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BodyChat>
        PARSER = new com.google.protobuf.AbstractParser<BodyChat>() {
      @java.lang.Override
      public BodyChat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BodyChat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BodyChat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BodyChat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.com.google.protobuf.proto.ProtocolBodyChat.BodyChat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_com_google_protobuf_proto_BodyChat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_com_google_protobuf_proto_BodyChat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ProtocolBodyChat.proto\022\036test.com.googl" +
      "e.protobuf.proto\"T\n\010BodyChat\022\014\n\004from\030\001 \001" +
      "(\005\022\020\n\010chatType\030\002 \001(\005\022\016\n\006roomId\030\003 \001(\005\022\n\n\002" +
      "to\030\004 \003(\005\022\014\n\004text\030\005 \003(\tB\022B\020ProtocolBodyCh" +
      "atb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_test_com_google_protobuf_proto_BodyChat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_com_google_protobuf_proto_BodyChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_com_google_protobuf_proto_BodyChat_descriptor,
        new java.lang.String[] { "From", "ChatType", "RoomId", "To", "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
